
CREATE TABLE IF NOT EXISTS "tgbot_place" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(255) NOT NULL);
--
-- Create model User
--
CREATE TABLE IF NOT EXISTS"tgbot_user" ("id" integer NOT NULL PRIMARY KEY, "name" varchar(100) NOT NULL, "age" integer NULL, "weight" numeric(5, 2) NULL, "height" numeric(5, 2) NULL, "gender" varchar(3) NULL, "lvl" integer NULL, "training_goal" text NULL, "place_id" bigint NULL);
--
-- Create model Training
--
CREATE TABLE IF NOT EXISTS"tgbot_training" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" text NOT NULL, "lvl" integer NOT NULL, "gender" varchar(3) NOT NULL, "type" varchar(255) NOT NULL, "description" text NOT NULL, "muscle_group" varchar(50) NOT NULL);
CREATE TABLE IF NOT EXISTS"tgbot_training_places" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "training_id" bigint NOT NULL, "place_id" bigint NOT NULL);
--
-- Create model Dnevnik


CREATE TABLE IF NOT EXISTS "tgbot_dnevnik" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "date" timestamp with time zone NOT NULL, "user_id" integer NOT NULL);
CREATE TABLE IF NOT EXISTS"tgbot_dnevnik_trainings" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "dnevnik_id" bigint NOT NULL, "training_id" bigint NOT NULL);
--ALTER TABLE "tgbot_user" ADD CONSTRAINT IF NOT EXISTS "tgbot_user_place_id_d9a0e388_fk_tgbot_place_id" FOREIGN KEY ("place_id") REFERENCES "tgbot_place" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX IF NOT EXISTS"tgbot_user_place_id_d9a0e388" ON "tgbot_user" ("place_id");
--
--ALTER TABLE  "tgbot_training_places" ADD CONSTRAINT IF NOT EXISTS "tgbot_training_places_training_id_place_id_3eb4b739_uniq" UNIQUE ("training_id", "place_id");
--ALTER TABLE "tgbot_training_places" ADD CONSTRAINT IF NOT EXISTS "tgbot_training_places_training_id_5acf5a1d_fk_tgbot_training_id" FOREIGN KEY ("training_id") REFERENCES "tgbot_training" ("id") DEFERRABLE INITIALLY DEFERRED;
--ALTER TABLE "tgbot_training_places" ADD CONSTRAINT IF NOT EXISTS "tgbot_training_places_place_id_81f46136_fk_tgbot_place_id" FOREIGN KEY ("place_id") REFERENCES "tgbot_place" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX IF NOT EXISTS "tgbot_training_places_training_id_5acf5a1d" ON "tgbot_training_places" ("training_id");
CREATE INDEX IF NOT EXISTS"tgbot_training_places_place_id_81f46136" ON "tgbot_training_places" ("place_id");
--
--ALTER TABLE  "tgbot_dnevnik" ADD CONSTRAINT IF NOT EXISTS "tgbot_dnevnik_user_id_899409f7_fk_tgbot_user_id" FOREIGN KEY ("user_id") REFERENCES "tgbot_user" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX IF NOT EXISTS "tgbot_dnevnik_user_id_899409f7" ON "tgbot_dnevnik" ("user_id");
--ALTER TABLE "tgbot_dnevnik_trainings" ADD CONSTRAINT IF NOT EXISTS "tgbot_dnevnik_trainings_dnevnik_id_training_id_02d6470b_uniq" UNIQUE ("dnevnik_id", "training_id");
--
--
--ALTER TABLE "tgbot_dnevnik_trainings" ADD CONSTRAINT IF NOT EXISTS "tgbot_dnevnik_trainings_dnevnik_id_a7468564_fk_tgbot_dnevnik_id" FOREIGN KEY ("dnevnik_id") REFERENCES "tgbot_dnevnik" ("id") DEFERRABLE INITIALLY DEFERRED;
--ALTER TABLE "tgbot_dnevnik_trainings" ADD CONSTRAINT  IF NOT EXISTS"tgbot_dnevnik_traini_training_id_b0bec7dd_fk_tgbot_tra" FOREIGN KEY ("training_id") REFERENCES "tgbot_training" ("id") DEFERRABLE INITIALLY DEFERRED;


CREATE INDEX IF NOT EXISTS "tgbot_dnevnik_trainings_dnevnik_id_a7468564" ON "tgbot_dnevnik_trainings" ("dnevnik_id");
CREATE INDEX IF NOT EXISTS "tgbot_dnevnik_trainings_training_id_b0bec7dd" ON "tgbot_dnevnik_trainings" ("training_id");
COMMIT;